name: compile LaTeX and release PDF

# トリガーは*.*.*のタグが付いたコミットがpushされた時
on:
  push:
    branch:
      - 'main'

permissions:
  actions: read
  checks: read
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      # TeXをcompile
      - name: compile latex document
        uses: ./.github/actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # compileしたpdfをアップロード
      - name: Push PDF file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name GH_ACTION
          git config user.email GH_ACTION
          cp *.pdf ./pdf
          git add ./pdf
          git commit -m "LaTeX compilation"
          git push
